name: build docker

on:
  push:
    branches: ['main']

jobs:
  build:
    # Name the Job
    name: Build docker image
    # Set the agent to run on
    runs-on: ubuntu-latest
    steps:
      - name: PrepareReg Names
        run: echo IMAGE_REPOSITORY=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]') >> $GITHUB_ENV
      - uses: docker/setup-buildx-action@v1
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Login to GitHub Package Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ env.IMAGE_REPOSITORY }}
          password: ${{ secrets.GHCR_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/${{ env.IMAGE_REPOSITORY }}:latest
