name: test docker

on:
  pull_request:
    branches: [main]

jobs:
  build:
    # Name the Job
    name: Build docker image
    # Set the agent to run on
    runs-on: ubuntu-latest
    steps:
      - name: PrepareReg Names
        run: echo ::set-env name=IMAGE_REPOSITORY::$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          push: false
          tags: |
            ghcr.io/${{ env.IMAGE_REPOSITORY }}/get_ec2_password:latest
